### PR TITLE
Switch from Travis-CI to GH Actions.

### PR DESCRIPTION
**Pull request by jsirois**

### CODE REVIEW

**Review by stuhood — APPROVED** [review]
Pre-approving. Thanks a lot for doing this!

**Review by benjyw — APPROVED** [review]
Nice! Thanks for doing this.

**Comment by jsirois** [comment]
@Eric-Arellano I wanted your take on ditching pyenv. It's not needed for CI anymore and it made both CI setup and the test code bigger / more complicated. You can still use pyenv as a dev (I do), you just need to make sure you've arranged that the needed Python versions are on your $PATH.

**Comment by jsirois** [comment]
I'm going to proceed with this @Eric-Arellano but I'll follow up if you point out something I've missed with ditching pyenv.

**Review by Eric-Arellano — COMMENTED** [review]
Sounds good on dropping Pyenv! I had thought we had a test for our Pyenv shim handling, but looks like not. That was the only thing I would have been worried about.

**Pull request merged**
