### PR TITLE
Run shfmt on scripts in this repo

### PR DESCRIPTION
**Pull request by asherf**
see: https://github.com/pantsbuild/setup/pull/139#issuecomment-1403839155  https://github.com/pantsbuild/setup/pull/138

### CODE REVIEW

**Comment by asherf** [comment]
@benjyw @stuhood

**Comment by asherf** [comment]
(reminder that I don't have merge permissions for this repo, so please when merge it when ready)

**Comment by benjyw** [comment]
I have a pending change to use Pants in this repo, which will give us shfmt, shellcheck and all the rest for free. So that might be a better path than manually adding this sort of thing.

**Comment by benjyw** [comment]
Going to close this due to https://github.com/pantsbuild/setup/pull/142

**Pull request closed without merging**
