### PR TITLE
Bump setuptools requirement to align with 1.3.0.dev3.

### PR DESCRIPTION
**Pull request by kwlzn**
```
[illuminati my_test_project]$ grep ^SETUPTOOLS pants
SETUPTOOLS_REQUIREMENT="setuptools>=5.4.1,<31.0"
```

```
[illuminati my_test_project]$ rm -rf ~/.cache ~/.pants.d ./.pants.d
[illuminati my_test_project]$ grep pants_version pants.ini
pants_version: 1.0.0
[illuminati my_test_project]$ ./pants help >/dev/null 2>&1; echo $?
0
```

```
[illuminati my_test_project]$ rm -rf ~/.cache ~/.pants.d ./.pants.d
[illuminati my_test_project]$ grep pants_version pants.ini
pants_version: 1.2.0
[illuminati my_test_project]$ ./pants help >/dev/null 2>&1; echo $?
0
```

```
[illuminati my_test_project]$ rm -rf ~/.cache ~/.pants.d ./.pants.d
[illuminati my_test_project]$ grep pants_version pants.ini
pants_version: 1.3.0.dev3
[illuminati my_test_project]$ ./pants help >/dev/null 2>&1; echo $?
0
```

### CODE REVIEW

**Comment by stuhood** [comment]
Can you confirm that this will allow for installing both older and newer versions?

**Comment by kwlzn** [comment]
@stuhood ah, I suppose older versions could still carry the 5.4.1 version - will lower the lower end of the range to accommodate.

**Comment by stuhood** [comment]
@kwlzn : Can probably cut it off to assume that only the `1.x.y`+ range is still relevant... but probably shouldn't drop support for installing 1.0.0 yet.

**Comment by kwlzn** [comment]
@stuhood 5.4.1 was the default version up until 1.3.x, so this should be the best range for compatibility. I just tested the setup process for 1.0.0/1.2.0/latest and all seem to resolve as expected.

**Review by jsirois — APPROVED** [review]

**Pull request merged**
