### PR TITLE
Ran shfmt on pantsup.sh

### PR DESCRIPTION
**Pull request by asherf**
see: https://github.com/pantsbuild/setup/pull/138

### CODE REVIEW

**Review by kaos — APPROVED** [review]
oh lord. I don't agree with all those formatting changes, but can't fight a tool for being consistent I guess :P

**Review by benjyw — APPROVED** [review]

**Comment by benjyw** [comment]
I like automatically-enforced consistency more than I dislike the actual formatting changes...

**Comment by asherf** [comment]
> I like automatically-enforced consistency more than I dislike the actual formatting changes...

@benjyw  working on it.... see: https://github.com/pantsbuild/setup/pull/138

**Comment by asherf** [comment]
someone please merge this since I don't have permissions.
thanks!

**Comment by jsirois** [comment]
This is very disappointing. I had all this set up over in scie-pants using our friend pants itself to fmt lint check.

**Comment by benjyw** [comment]
I could figure out how to route static.pantsbuild.org/pantsup.sh to the scie-pants repo instead of the setup repo, if you think that's preferable. That was why I moved the script to the setup repo, so as not to have to tinker with our Google Analytics stuff, but looks like I will have to tinker anyway due to the final sunsetting of Universal Analytics in favor of GA4 in a few months.

**Pull request merged**
